development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://localhost:5432/OAuth2_SAMPLE_development') %>

test:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://localhost:5432/OAuth2_SAMPLE_test') %>

staging:
  <<: *default

production:
  <<: *default
